# Generated by Django 5.2.12 on 2026-03-18 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipousuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='login.tipousuario'),
            preserve_default=False,
        ),
    ]
