# Generated by Django 6.0.2 on 2026-03-02 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_corto_empresa', models.CharField(max_length=200)),
                ('descripcion_empresa', models.CharField(max_length=500)),
                ('texto_portada', models.CharField(max_length=50)),
                ('descripcion_portada', models.CharField(max_length=200)),
                ('fc_crea', models.DateTimeField(auto_now_add=True)),
                ('user_crea', models.CharField(max_length=100)),
                ('fc_modi', models.DateTimeField(auto_now=True)),
                ('user_modi', models.CharField(max_length=100)),
                ('fc_baja', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-nombre_empresa'],
            },
        ),
    ]
