# Generated by Django 6.0.2 on 2026-03-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fc_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
