# Generated by Django 6.0.2 on 2026-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_empresa_fc_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
