# Generated by Django 6.0.2 on 2026-03-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_empresa_nombre_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=100, unique=True)),
                ('seccion_menu', models.CharField(max_length=100)),
                ('titulo_menu', models.CharField(max_length=100)),
                ('contenido_menu', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido_link', models.CharField(blank=True, max_length=200, null=True)),
                ('fc_crea', models.DateTimeField(auto_now_add=True)),
                ('user_crea', models.CharField(max_length=100)),
                ('fc_modi', models.DateTimeField(auto_now=True)),
                ('user_modi', models.CharField(max_length=100)),
                ('fc_baja', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='principal.empresa')),
            ],
            options={
                'ordering': ['-nombre_menu'],
            },
        ),
    ]
