# Generated by Django 6.0.2 on 2026-03-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-orden']},
        ),
        migrations.AddField(
            model_name='menu',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
