# Generated by Django 6.0.2 on 2026-03-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_menu_options_menu_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo', models.CharField(max_length=200)),
                ('fc_crea', models.DateTimeField(auto_now_add=True)),
                ('user_crea', models.CharField(max_length=100)),
                ('fc_modi', models.DateTimeField(auto_now=True)),
                ('user_modi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-descripcion_tipo'],
            },
        ),
    ]
