# Generated by Django 6.0.2 on 2026-03-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_tipoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoempresa',
            name='fc_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
