# Generated by Django 6.0.2 on 2026-03-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_tipoempresa_fc_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipoempresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.tipoempresa'),
            preserve_default=False,
        ),
    ]
