# Generated by Django 6.0.2 on 2026-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_empresa_tipoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoempresa',
            name='cdtipo',
            field=models.CharField(default='E', max_length=3),
            preserve_default=False,
        ),
    ]
