# Generated by Django 6.0.2 on 2026-03-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_tipoempresa_cdtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link_comunidad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_instragram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_otra_comunidad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_tiktok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_twiter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
