# Generated by Django 6.0.2 on 2026-03-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_empresa_link_comunidad_empresa_link_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='link_instragram',
            new_name='link_instagram',
        ),
    ]
