# Generated by Django 6.0.2 on 2026-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_rename_link_instragram_empresa_link_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_corporativo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
