# Generated by Django 5.2.12 on 2026-03-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtipo', models.CharField(max_length=4, unique=True)),
                ('descripcion_tipo', models.CharField(max_length=100)),
                ('fc_crea', models.DateTimeField(auto_now_add=True)),
                ('user_crea', models.CharField(max_length=100)),
                ('fc_modi', models.DateTimeField(auto_now=True)),
                ('user_modi', models.CharField(max_length=100)),
                ('fc_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-descripcion_tipo'],
            },
        ),
    ]
