# Generated by Django 6.0.2 on 2026-03-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link_portada',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
