# Generated by Django 6.0.2 on 2026-03-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_link_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='user',
        ),
    ]
