# Generated by Django 6.0.2 on 2026-03-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_curso_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_crea', models.DateTimeField(auto_now_add=True)),
                ('user_crea', models.CharField(max_length=100)),
                ('fc_modi', models.DateTimeField(auto_now=True)),
                ('user_modi', models.CharField(max_length=100)),
                ('fc_baja', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='asignacion',
            field=models.ManyToManyField(related_name='cursos', through='cursos.AsignacionCurso', to=settings.AUTH_USER_MODEL),
        ),
    ]
