# Generated by Django 6.0.2 on 2026-03-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_asignacioncurso_curso_asignacion'),
        ('principal', '0009_tipoempresa_cdtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.empresa'),
            preserve_default=False,
        ),
    ]
