# Generated by Django 6.0.2 on 2026-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cdmodal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
