# Generated by Django 6.0.2 on 2026-03-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_cdmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='objetivo_curso',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
